name: Feature Request
description: New feature request. Request to add some new functionality or improve the existing ones.
title: "Summarize your request."
labels: [feature request]

body:

- type: checkboxes
  attributes:
    label: "Checklist"
    options:
      - label: "I have searched for [similar issues](https://github.com/drprojects/superpoint_transformer/issues)."
        required: true
      - label: " I have tested with the lastest available version."
        required: true
      - label: "I have checked the [introduction page](https://github.com/drprojects/superpoint_transformer/blob/master/README.md ) and the [documentation](https://github.com/drprojects/superpoint_transformer/tree/master/docs) "
        required: true

- type: textarea
  attributes:
    description: >
        Describe what feature you'd like to have in SuperPoint Transformers.
    label: "Proposed new feature or change"
  validations:
    required: true

- type: textarea
  attributes:
    label: "References"
    description: Please share some references that can help us know more about this feature and try to implement the same. For ex. research paper, open-source codes, stackoverflow, etc.

- type: textarea
  attributes:
    label: "Additional information"
    description: Add any other context or screenshots about the feature request here.